# syntax=docker/dockerfile:1

FROM gha-runner-base

ARG RUNNER_VERSION="2.317.0"

RUN <<EOF

ARCH=`dpkg --print-architecture | sed --expression='s/amd/x/g'`
FILENAME=actions-runner-linux-${ARCH}-${RUNNER_VERSION}.tar.gz
curl -O -L https://github.com/actions/runner/releases/download/v${RUNNER_VERSION}/${FILENAME}
tar xzf ./$FILENAME
rm ./$FILENAME

EOF

COPY --chown=docker:docker misc/start.sh /home/docker/actions-runner/start.sh
ENTRYPOINT ["/bin/bash", "-l", "-c"]
CMD ["./start.sh"]
